### ISSUE TITLE
MemoryError: std::bad_alloc when importing model 

### ISSUE THREAD

**Issue by gurolcay** [eske/word2vecpp-legacy#13]
```
Python 2.7.14 (default, Sep 23 2017, 22:06:14) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from multivec import BilingualModel
>>> model = BilingualModel("/home/gurol/Documents/Bil496/Code/multivec/models/OpenSubtitles2018.en-tr.bin")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "multivec.pyx", line 357, in multivec.BilingualModel.__cinit__
    self.model.load(name)
MemoryError: std::bad_alloc
```
I take above error message when trained model importing on ubuntu 17.10. This model train on ubuntu 17.10. But I don't take same message when I use model which is trained on osx. 

On my ubuntu:
g++ version: 
```
g++ --version
g++ (Ubuntu 7.2.0-8ubuntu3.2) 7.2.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
cmake version:
```
cmake version 3.9.1
```

**Comment by gurolcay** [comment]
I train a model again with 16 thread, it is working now. Previous train was made with 100 thread.
